name: Latest blog post Website
on:
  schedule:
    # Runs every hour
    - cron: '0 0 * * *' # runs at every 12AM UTC

  # This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: 'https://joseluisgs.github.io/rss'
          date_format: 'd mmm yyyy'
          template: '$newline - ✏️ [**$title**]($url) 🗓 *$date* $newline'
          # template: '<table><tr><td><a href="$url"><img width="60px" src="https://joseluisgs.github.io/img/web-social.png"></a></td>$newline<td><a href="$url">$title</a><br/>$date</td></tr></table>$newline'
